service: whatsapp-webhooks
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:xxxxxxxxxxxx:table/reviews"
  environment:
    TOKEN: ${env:APP_TOKEN}
    REVIEW_TABLE: reviews

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    ReviewsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.REVIEW_TABLE}
        AttributeDefinitions:
          - AttributeName: phonenumber
            AttributeType: S
        KeySchema:
          - AttributeName: phonenumber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1